"""
============================================================
 PHASE 1 - STEP 4 : PREPROCESSING & FEATURE ENGINEERING
============================================================
This module is the SINGLE source of truth for how raw sensor
readings become model inputs. It is imported by:

    * the training script          (src/models/train_model.py)
    * the live inference service   (backend/services/predictor.py)

so the transformation applied at 3 a.m. in the factory is
byte-for-byte the transformation used during training. This is the
most common cause of silent failure in deployed ML systems, and
sharing one module removes it entirely.

--------------------------------------------------------------------
 WHY THESE FEATURES - AND WHY NOT MORE
--------------------------------------------------------------------
 The AI4I failure labels are generated by threshold rules on
 derived physical quantities. It would therefore be trivial to
 hand the model features such as

        power_margin  = power - 3500
        strain_margin = osf_limit(type) - tool_wear * torque

 which are literally the signed distance to the decision boundary.
 The model would score ~100% and would have learned nothing: this is
 TARGET LEAKAGE dressed up as feature engineering.

 So we deliberately provide only the derived quantities a maintenance
 engineer would compute anyway from first principles -

        temp_delta          thermal gradient across the machine
        power               mechanical power actually delivered
        strain              cumulative mechanical stress on the tool
        torque_speed_ratio  load characteristic of the drive

 - and let the Random Forest DISCOVER the thresholds from the data.
 Feature importances then mean something, and the reported accuracy
 reflects genuine learning.

 NOTE ON SCALING: no StandardScaler / MinMaxScaler is applied.
 Random Forest splits on axis-aligned thresholds within a single
 feature, so it is invariant to any monotone rescaling. Adding a
 scaler would cost inference time and buy exactly nothing.
--------------------------------------------------------------------
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.config import MACHINE_TYPES

# Ordinal because the variants are an ordered quality scale L < M < H
TYPE_CODE = {t: i for i, t in enumerate(MACHINE_TYPES)}

# The exact feature vector the model consumes, in order.
FEATURE_COLUMNS = [
    "air_temperature",
    "process_temperature",
    "rotational_speed",
    "torque",
    "tool_wear",
    "type_code",
    "temp_delta",
    "power",
    "strain",
    "torque_speed_ratio",
]

# Human-readable names for the HMI's explainability panel
FEATURE_LABELS = {
    "air_temperature": "Air Temperature",
    "process_temperature": "Process Temperature",
    "rotational_speed": "Rotational Speed",
    "torque": "Torque",
    "tool_wear": "Tool Wear",
    "type_code": "Machine Variant",
    "temp_delta": "Thermal Gradient (dT)",
    "power": "Mechanical Power",
    "strain": "Tool Strain (wear x torque)",
    "torque_speed_ratio": "Load Characteristic",
}

FEATURE_UNITS = {
    "air_temperature": "K",
    "process_temperature": "K",
    "rotational_speed": "rpm",
    "torque": "Nm",
    "tool_wear": "min",
    "type_code": "",
    "temp_delta": "K",
    "power": "W",
    "strain": "minNm",
    "torque_speed_ratio": "Nm/rpm",
}

RAW_INPUT_COLUMNS = [
    "machine_type",
    "air_temperature",
    "process_temperature",
    "rotational_speed",
    "torque",
    "tool_wear",
]


# ==================================================================
#  DERIVED PHYSICS
# ==================================================================
def add_physics(df: pd.DataFrame) -> pd.DataFrame:
    """Attach the four derived engineering quantities."""
    out = df.copy()

    # thermal gradient the cooling system has to maintain
    out["temp_delta"] = out["process_temperature"] - out["air_temperature"]

    # mechanical power  P = T * omega,  omega = 2*pi*N/60
    out["power"] = out["torque"] * out["rotational_speed"] * 2.0 * np.pi / 60.0

    # cumulative mechanical stress carried by the cutting tool
    out["strain"] = out["tool_wear"] * out["torque"]

    # drive load characteristic (guarded against divide-by-zero)
    out["torque_speed_ratio"] = out["torque"] / out["rotational_speed"].replace(0, np.nan)
    out["torque_speed_ratio"] = out["torque_speed_ratio"].fillna(0.0)

    return out


def encode_type(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["type_code"] = (
        out["machine_type"].astype(str).str.strip().str.upper().map(TYPE_CODE)
    )
    # an unknown variant defaults to L, the most common and most fragile
    out["type_code"] = out["type_code"].fillna(TYPE_CODE["L"]).astype(int)
    return out


# ==================================================================
#  PUBLIC API
# ==================================================================
def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Raw sensor frame -> full feature frame (all original columns kept)."""
    return add_physics(encode_type(df))


def to_matrix(df: pd.DataFrame) -> pd.DataFrame:
    """Feature frame -> the exact ordered matrix the model expects."""
    engineered = df if "temp_delta" in df.columns else engineer_features(df)
    missing = [c for c in FEATURE_COLUMNS if c not in engineered.columns]
    if missing:
        raise KeyError("Missing engineered feature columns: {}".format(missing))
    return engineered[FEATURE_COLUMNS].astype(float)


# ==================================================================
#  CLEANING
# ==================================================================
def clean(df: pd.DataFrame, verbose: bool = True) -> pd.DataFrame:
    """
    Remove rows that cannot physically exist. Deliberately conservative:
    we drop impossibilities, not statistical outliers. A torque spike IS
    the fault we are trying to catch - discarding it would delete exactly
    the signal the model needs.
    """
    n0 = len(df)
    out = df.copy()

    # 1. required fields must be present
    out = out.dropna(subset=RAW_INPUT_COLUMNS)
    n_na = n0 - len(out)

    # 2. physically impossible values
    impossible = (
        (out["rotational_speed"] <= 0)
        | (out["torque"] < 0)
        | (out["tool_wear"] < 0)
        | (out["air_temperature"] <= 0)
        | (out["process_temperature"] <= 0)
    )
    n_imp = int(impossible.sum())
    out = out[~impossible]

    # 3. exact duplicate sensor readings carry no extra information
    before = len(out)
    out = out.drop_duplicates(subset=RAW_INPUT_COLUMNS + ["failure_class"]) \
        if "failure_class" in out.columns else out.drop_duplicates(subset=RAW_INPUT_COLUMNS)
    n_dup = before - len(out)

    if verbose:
        print("  Cleaning:")
        print("    rows in                 : {:,}".format(n0))
        print("    dropped - missing fields: {:,}".format(n_na))
        print("    dropped - impossible    : {:,}".format(n_imp))
        print("    dropped - duplicates    : {:,}".format(n_dup))
        print("    rows out                : {:,}".format(len(out)))

    return out.reset_index(drop=True)


# ==================================================================
#  GROUPS - to prevent temporal leakage between train and test
# ==================================================================
def build_groups(df: pd.DataFrame) -> np.ndarray:
    """
    Consecutive readings from ONE simulated machine are strongly
    autocorrelated. A plain random split would put reading #240 in
    train and reading #241 in test, and the reported accuracy would be
    measuring memorisation, not generalisation.

    So every simulated machine forms ONE group and never appears on
    both sides of a split. The 10,000 real AI4I rows are independent
    product snapshots, so each becomes its own singleton group.
    """
    is_synth = df["source"].eq("SYNTH-RUN2FAIL") if "source" in df.columns \
        else pd.Series(True, index=df.index)

    groups = np.where(
        is_synth,
        df["machine_id"].astype(str),
        "AI4I_" + df.index.astype(str),
    )
    return groups
